#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
from app import engine

if __name__ == "__main__":
    if len(sys.argv) > 1:
        if sys.argv[1].lower() == "initdb":
            try:
                from app.scripts import initdb
                initdb()
            except Exception as e:
                print('Error', e)
            sys.exit(0)

        if sys.argv[1].lower() == "seggment":
            try:
                from app.scripts.train import train_seggment
                train_seggment()
            except Exception as e:
                print('Error', e)
            sys.exit(0)

        if sys.argv[1].lower() == "tagger":
            try:
                from app.scripts.train import train_tagger
                train_tagger()
            except Exception as e:
                print('Error', e)
            sys.exit(0)

    if engine.config["DEBUG"] == False:
        import logging
        log = logging.getLogger('werkzeug')
        log.disabled = True
        engine.logger.disabled = True

    engine.run('0.0.0.0', port=engine.config["PORT"])
